### ISSUE TITLE
Contract mismatch  for qr-code return value (void? vs boolean?)

### ISSUE THREAD

**Issue by amcvega** [simmone/racket-simple-qr#1]
Hi I used your excellent library in a typed/racket script of mine and I noticed that the contract violation for the `qr-code`. The `save-file` function apparently returns a `boolean?` value instead of `void?`

My workaround was to add (void) at the end of the definition for `qr-code`

**Comment by simmone** [comment]
Yes, you're right, I added (void) at the end of the qr-code function.

I'm glad to know you're using the simple-qr lib, I complete the first
version not a long time ago.

If you find any problem or suggestion, please let me know.

2015-07-31 10:01 GMT+08:00 amcvega notifications@github.com:
