### ISSUE TITLE
Error with long URLs

### ISSUE THREAD

**Issue by srfoster** [simmone/racket-simple-qr#3]
Thanks for making this library.  I've used it successfully in several Racket projects.

I've noticed an error when longish URLs are written out, e.g.

```
(qr-write "https://gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogle.com" "normal.png")
```

This, however, works:

```
(qr-write "https://goooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogle.com" "normal.png")
```

Here's some error info:

![screen shot 2018-10-17 at 1 13 15 pm](https://user-images.githubusercontent.com/764563/47113709-91a9ce80-d20e-11e8-9789-6ac0342463de.png)

Obviously, I could work around this by using a URL shortening service.  But I do think this suggests a bug of some sort in qr-write.  What do you think?

**Comment by simmone** [comment]
It's bug indeed, thank you for use and report the bug.

**Comment by simmone** [comment]
@srfoster 

1. bug fixed, please raco pkg update simple-qr and verify.

2. for search bug, add a express? argument to generate qr code read and write details.
    very slow, for debug use only.

Thank you again, I find several very very big bugs in this lib.
